# Generated by Django 5.1.7 on 2025-04-13 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название поста')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='лайки')),
                ('dislikes', models.PositiveBigIntegerField(default=0, verbose_name='дизлайки')),
                ('user', models.ForeignKey(default='Unknown author', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/posts/', verbose_name='изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.posts', verbose_name='статья')),
            ],
        ),
    ]
