# Generated by Django 5.1.7 on 2025-04-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('id',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('id',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
