# Generated by Django 5.1.7 on 2025-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_images_options_alter_posts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название категории')),
                ('post', models.ManyToManyField(blank=True, related_name='related_post', to='posts.posts', verbose_name='связанный пост')),
            ],
        ),
    ]
