# Generated by Django 5.1.7 on 2025-04-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
