# Generated by Django 5.1.7 on 2025-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_categories_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(related_name='post_categories', to='posts.categories', verbose_name='категории поста'),
        ),
    ]
