# Generated by Django 5.1.7 on 2025-04-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_categories_post_posts_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='posts.posts', verbose_name='статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reactions', to=settings.AUTH_USER_MODEL, verbose_name='реактор')),
            ],
        ),
    ]
