# Generated by Django 5.1.7 on 2025-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(max_length=10, verbose_name='реакция юзера'),
        ),
    ]
