# Generated by Django 5.1.7 on 2025-04-13 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст комментария')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='лайки')),
                ('dislikes', models.PositiveBigIntegerField(default=0, verbose_name='дизлайки')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_comment', to='comments.comments', verbose_name='родительский комментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='posts.posts', verbose_name='родительский пост')),
                ('user', models.ForeignKey(default='Unknown author', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
