# Generated by Django 5.1.7 on 2025-03-23 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='никнейм')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('birthday', models.DateField(blank=True, verbose_name='дата рождения')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='эл. почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='администратор')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='пол')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('groups', models.ManyToManyField(blank=True, related_name='client_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='client_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('id',),
            },
        ),
    ]
