# Generated by Django 5.1.7 on 2025-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_birthday_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='код активации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
    ]
